Manacher's Algo added by wizeewig
wingkwong/leetcode-the-hard-way pull request #100
Opened 2022-09-30 19:38 UTC by wizeewig

Added the full documentation for Manacher's Algorithm.

2022-10-01 03:20 UTC, wingkwong requested changes
1. Your changes break the site. Please run the app locally instead of just writing on a markdown editor.

![image](https://user-images.githubusercontent.com/35857179/193383828-3ea08fb0-3654-476f-815d-c2938e5aabb8.png)

2. Use LaTex. e.g. `O(N³)` -> `$O(N ^ 3)$ so it renders like $O(N ^ 3)$ instead of O(N³).

3. I found that most content is just copied from other sites like GFG and Scaler. Please don't do that.

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +```C++
use cpp instead

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +* if the given string is “abcbabcbabcba”, the output should be “abcbabcbabcba”
1. don't copy from GFG. 
2. give a brief context on what palindrome is
3. besides you should include one that the longest palindromic substring is not same as the original string. i.e. the one you deleted from that site.

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +No extra space is needed in this approach, so the space complexity will be O(1).
some line breaks

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +### Time complexity O(N³)
remove `O(N³)` from the title

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +### Space complexity O(1)
remove `O(1)` from the title

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +* ## Manacher's Algorithm
unnecessary `*`

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +
The content starting from this line is copied from https://www.scaler.com/topics/data-structures/manachers-algorithm/. What's the point of copying other content exactly?

2022-10-01 03:20 UTC, wingkwong commented on tutorials/strings/manachers-algorithm.md
> +- [@wizeewig](https://www.github.com/wizeewig)
Remove this. Use the following. See other tutorials for reference.

```
<TutorialAuthors names="@xxxxxx"/>
```

2022-10-01 08:51 UTC, wizeewig commented
Ok. Will do the changes.

2022-10-02 02:18 UTC, wingkwong requested changes
1. Proofreading first
2. There is not point to duplicate the page title at L14. It's better to call Overview. 
3. I don't see you walk through the algo using LC problems 
4. I don't see the suggested problems at the end
5. Apply LaText on time / space complexity or even those string instead of using `"`. e.g. "abigsquare" -> $abigsquare$

2022-10-02 06:04 UTC, wizeewig commented
Ok.

2022-10-04 03:26 UTC, wingkwong requested changes
https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#tutorials

2022-11-01 16:07 UTC, wingkwong commented
any update?

2022-11-02 08:07 UTC, wingkwong commented
ref: #71

2022-11-18 11:40 UTC, closed without merging

2023-10-01 17:50 UTC, abhiramtilakiiit commented
I might take this up. Also what syntax checker should I use?

2023-10-01 17:51 UTC, wingkwong commented
@abhiramtilakiiit leave a comment in above issue so that I could assign you.