Added 1503 solutions
wingkwong/leetcode-the-hard-way pull request #116
Opened 2022-10-01 13:57 UTC by WaqarTabish2807

Added different solutions for the question.

2022-10-01 14:38 UTC, wingkwong requested changes
Run the app and verify locally first please. Can't even start the app with your broken changes.

2022-10-01 14:38 UTC, wingkwong commented on solutions/1500-1599/1503-Last-Moment-Before-All-Ants-Fall-Out-of-a-Plan.md
> +description: 'Author: @wingkwong | https://leetcode.com/problems/last-moment-before-all-ants-fall-out-of-a-plank/'
Don't use my name

2022-10-01 15:39 UTC, WaqarTabish2807 commented
I ran these on leetcode locally, and all the codes are running without an error. Let me know what changes does it require?

2022-10-01 16:12 UTC, wingkwong commented
Not your code. Run the app locally.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/35857179/193418350-865271b8-2b0a-4ecf-84f9-eb8325bdf637.png">

2022-10-01 18:19 UTC, WaqarTabish2807 commented
hey, @wingkwong I am unable to get your comment. Can you please brief it?

2022-10-02 03:32 UTC, wingkwong commented
@WaqarTabish2807 I build this site using docusaurus. When you fork my repository, you need to clone it to your local machine. Then navigate to the root and run those commands to start the development server. When you start it, a browser window will open at http://localhost:3000/. I could see the error thrown from your page. 

You should verify the changes there, not in a markdown editor.

```bash
cd leetcode-the-hard-way
npm i 
npm run start
# By default, a browser window will open at http://localhost:3000/.
```

2022-10-03 13:24 UTC, closed without merging