0162. Find Peak Element
wingkwong/leetcode-the-hard-way pull request #133
Opened 2022-10-02 07:26 UTC by Rittika1234

2022-10-02 08:28 UTC, wingkwong commented
Next time please don't close and open a new PR. you can just push the changes to your branch and the changes will be reflected in the PR automatically.

2022-10-02 08:41 UTC, Rittika1234 commented
Okay Sorry. I will not do this next time.  Please check my PR.

2022-10-02 08:55 UTC, wingkwong requested changes
Do you think this is ready for review? Please look at other pages and verify it locally first.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/35857179/193446231-0d460c23-832e-4c5a-85a7-428b428a0713.png">

2022-10-03 07:55 UTC, Rittika1234 commented
Check my PR

2022-10-03 08:05 UTC, wingkwong requested changes

2022-10-03 08:05 UTC, wingkwong commented on solutions/0100-0199/0162.Find Peak Element.md
> +Space complexity:  $O(1)$
these will be rendered in one line in the site which results in poor readability. I highly suggest you to start the app locally and verify first.

2022-10-03 08:05 UTC, wingkwong commented on solutions/0100-0199/0162.Find Peak Element.md
> +Space complexity: $O(1)$
these will be rendered in one line in the site which results in poor readability. I highly suggest you to start the app locally and verify first.

2022-10-03 08:05 UTC, wingkwong commented on solutions/0100-0199/0162.Find Peak Element.md
> +```
where is the explanation ?? what is the intuition of `arr[mid] > arr[mid+1]` ?

2022-10-03 08:05 UTC, wingkwong commented on solutions/0100-0199/0162.Find Peak Element.md
> +This is a brute force approach. We traverse each element and check whether it is greater than to max value.If we find one, than we initialize this value to max, return max value.
The statement `If we find one, than we initialize this value to max, return max value.` is not accurate and doesn't match with your code.  $max$ is updated as long as it meets a larger number, not just "initialize" and  return.

2022-10-03 08:15 UTC, closed without merging