bucket-sort
wingkwong/leetcode-the-hard-way pull request #134
Opened 2022-10-02 07:29 UTC by flow6979

2022-10-02 08:47 UTC, flow6979 commented
Hey @wingkwong please review my PR and merge it or suggest some changes if you want

2022-10-02 08:50 UTC, wingkwong requested changes
Please see [here](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#tutorials) first..

2022-10-02 09:23 UTC, flow6979 commented
HEY @wingkwong I have done according to what you said. still if you want some change please ping me.
if my PR is fine please merge it.
Thank you.

2022-10-02 11:55 UTC, flow6979 commented
hey brother @wingkwong please review it

2022-10-02 12:46 UTC, wingkwong requested changes
DON'T COPY CONTENT FROM OTHER SITES.

2022-10-02 12:46 UTC, wingkwong commented on tutorials/basic-topics/sorting/bucket-sort.md
> +```C++
1. wrong format. Use `<Tabs>` to wrap it.
2. use a LC problem to walk through the topic.

2022-10-02 12:46 UTC, wingkwong commented on tutorials/basic-topics/sorting/bucket-sort.md
> +    "solutionLink": "../../../solutions/0300-0399/0347 - Top K Frequent Elements"
i don't think this link would work. Have you ever verified it once before requesting review?

2022-10-02 12:46 UTC, wingkwong commented on tutorials/basic-topics/sorting/bucket-sort.md
> +description: 'bucket sort is one of the famous sorting algorithm.'
that is a bad description

2022-10-02 12:46 UTC, wingkwong commented on tutorials/basic-topics/sorting/bucket-sort.md
> +title: 'The Bucket Sort Algorithm'
revert to Bucket Sort please

2022-10-02 12:46 UTC, wingkwong commented on solutions/0300-0399/0347 - Top K Frequent Elements.md
> +```cpp
wrong format. Use <Tabs>. See `CONTRIBUTING.md` first please.

2022-10-02 12:46 UTC, wingkwong commented on tutorials/basic-topics/sorting/bucket-sort.md
> +This means that the hash function we use must meet this requirement
What's the point of copying the exact content from https://github.com/akarazhev/algorithms-structures-patterns/blob/master/algorithms/doc/bucket-sort.md ?

2022-10-02 12:49 UTC, flow6979 commented
> DON'T COPY CONTENT FROM OTHER SITES.

brother i have not copied code and explanation.. but things like time complexity, you cant do anything with that, it needs to be seen from somewhere.

IF YOU WANT SOMETHING SPECIFIC TO BE CHANGED..tell me

2022-10-02 13:18 UTC, wingkwong commented
First, that's from other people work. You didn't even give a credit. Time Complexity and Space Complexity are fine. You're just copying the exact content even with the author's bad formatting. 

Please redo it. I won't accept this kind of work.

2022-10-02 13:56 UTC, flow6979 commented
ok i will do it myself again

2022-10-22 05:19 UTC, wingkwong commented
Any update?

2022-11-01 16:07 UTC, wingkwong commented
any update?

2022-11-18 11:41 UTC, wingkwong commented
Closing due to inactivity.

2022-11-18 11:41 UTC, closed without merging