adding solution: 0088  Merge Sorted Array, codes written in java
wingkwong/leetcode-the-hard-way pull request #143
Opened 2022-10-03 13:18 UTC by deepanshu-rawat6

Merge Sorted Array (Easy) solved using two approaches(brute force[sorting] and two pointers) in java

2022-10-03 14:30 UTC, deepanshu-rawat6 commented
@wingkwong Ma'am are the issue fixed now?

2022-10-03 14:38 UTC, wingkwong requested changes

2022-10-03 14:38 UTC, wingkwong commented on solutions/0000-0099/0088-merge-sorted-array-easy.md
> +This solution gives O(m+n) or O(N) time complexity and O(m) or O(N) space complexity.
- Don't use backtick. Use LaTex instead.
- Use LaTex on Time complexity and Space complexity as well.
- for all operators, add spaces. e.g. 
  - `m+n` -> `m + n`. 
  - `while(i<m && j<n)` -> `while ( i < m && j < n)`

2022-10-03 14:38 UTC, wingkwong commented on solutions/0000-0099/0088-merge-sorted-array-easy.md
> +```
suggest to add some comments so that beginners can follow. add it above the line

2022-10-03 14:38 UTC, wingkwong commented on solutions/0000-0099/0088-merge-sorted-array-easy.md
> +</Tabs>
- Don't use backtick. Use LaTex instead.
- Use LaTex on Time complexity and Space complexity as well.
- for all operators, add spaces. e.g. 
  - `m+n` -> `m + n`. 
  - `for(int i=0;i<n;i++)` -> `for (int i = 0; i < n; i++)`

2022-10-03 14:38 UTC, wingkwong commented on solutions/0000-0099/0088-merge-sorted-array-easy.md
> +## Approach 2: Two Pointer Approach
`## Approach 2: Two Pointer Approach` -> `## Approach 2: Two Pointers`

2022-10-03 14:38 UTC, wingkwong commented on solutions/0000-0099/0088-merge-sorted-array-easy.md
> +## Approach 1: Brute Force(Sorting)
`## Approach 1: Brute Force(Sorting)` -> `## Approach 1: Brute Force`

2022-10-03 18:45 UTC, deepanshu-rawat6 commented
@wingkwong is it fixed now?

2022-10-04 02:23 UTC, wingkwong approved these changes
overall it looks ok. I'll clean up a bit.

2022-10-04 02:24 UTC, merged