Mod 1e9+7 Tutorial
wingkwong/leetcode-the-hard-way pull request #170
Opened 2022-10-04 09:58 UTC by tannudaral

Please let me know if any changes are required.

2022-10-04 11:26 UTC, wingkwong requested changes
If you've referenced some external sites, state them at the end.

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +Sometimes, the answer to a problem is a very large number but it is enough to output it "modulo m", i.e., the remainder when the answer is divided by m (for example, "modulo 1e9 + 7"). The idea is th
I think this intro is from CP handbook. If so, don't copy the exact content from other sources, use your own words to describe it.

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +The task of modulo operator `%`, also know as the remainder operator, is to give the remainder. We denote by x mod m, the remainder when x is divided by m. For example, $17\,mod\,5= 2$ because 17 = 3
Don't use backtick. Use LaTex. Apply to all.

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +#### 1. Addition
add a line break before L24

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +  $(a\,−\,b)\,mod\,m$ $=$ $(a \, mod\, m \,−\, b \,mod \,m\, + \,m)\, mod \,m$
remove the extra space at the beginning

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +                            // Here, fact may exceed 2^64-1
put the comment above that line

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +                                  // exceeds 10^9+7
put the comment above that line

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +    int M = 1e9+7;
add space. `1e9 + 7`

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +    int M = 1e9+7;
add space. `1e9 + 7`

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +    return fact%M;
add space. i.e. `fact % M`

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +
space for 1e9 + 7

2022-10-04 11:26 UTC, wingkwong commented on tutorials/basic-topics/mod.md
> +```cpp
Use `<Tabs/>` for code.

See [here](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md#solutions)

2022-10-05 08:28 UTC, vigneshshiv reviewed
Overall looks good, Few changes needed, go through the comments

2022-10-05 08:28 UTC, vigneshshiv commented on tutorials/basic-topics/mod.md
> +
Space not added yet.

2022-10-05 08:28 UTC, vigneshshiv commented on tutorials/basic-topics/mod.md
> +The task of modulo operator $\%$, also know as the remainder operator, is to give the remainder. We denote it by $x\,mod\,m$, the remainder when $x$ is divided by $m$. For example, 17 mod 5 = 2 becau
Use LaTeX when you specify numbers

2022-10-05 14:19 UTC, tannudaral commented
Made all requested changes. Pls check!

2022-10-05 17:07 UTC, vigneshshiv reviewed
All good, one more round final changes.

2022-10-05 17:07 UTC, vigneshshiv commented on tutorials/basic-topics/mod.md
> +int factorial(int n){
Leave space between **) {**

2022-10-05 17:07 UTC, vigneshshiv commented on tutorials/basic-topics/mod.md
> +int factorial(int n){
Leave space between **) {**

2022-10-06 03:17 UTC, tannudaral commented on tutorials/basic-topics/mod.md
> +int factorial(int n){
Done. Pls check!

2022-10-06 04:25 UTC, vigneshshiv approved these changes
Looks good.

2022-10-06 05:17 UTC, wingkwong approved these changes
Overall it looks ok. Will fine tune a bit myself.

2022-10-06 05:17 UTC, merged

2022-10-06 05:24 UTC, wingkwong commented
@tannudaral cleaned up a bit and published. Thank you very much!