Added solution of 0102
wingkwong/leetcode-the-hard-way pull request #188
Opened 2022-10-06 05:08 UTC by Srijita-Mandal

## Change Summary

I added the solution of the leetcode problem 0102

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [ ] Make sure you've applied LaTex for variables or formulas
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`). 
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary.
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [x] Make sure you've explained your code well (write comments above each line)
- [x] Make sure you've written your explanation well and it is easy to understand for beginners
- [x] Make sure you've included Time & Space Complexity Analysis 

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).
- [ ] Make sure you've included a meaningful approach name

2022-10-06 05:15 UTC, wingkwong requested changes
Rejected. Please look at the checklist again.

2022-10-06 05:31 UTC, Srijita-Mandal commented
@wingkwong I have checked the list

2022-10-06 05:40 UTC, wingkwong requested changes
I suggest you to read the checklist again. Not just tick them without checking.

Besides, you deleted my `package-lock.json`. don't commit that.

2022-10-06 05:40 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +};
1. the code format is already wrong. See General point 5.
2. comments should be above each line. not inline. See General point 6.

2022-10-06 05:40 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +- If the node is not null, push the value into `v` and push its left and right nodes into queue (if not null).
use LaTex, not backtick

2022-10-06 05:40 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +**Time Complexity:**  O(N)
1. Apply LaTex. See General point 4.
2. Missing Space Complexity. See General point 8.

2022-10-07 13:35 UTC, Srijita-Mandal commented
@wingkwong I have made the changes. Please check if it is okay now.

2022-10-07 16:07 UTC, vigneshshiv requested changes
package-lock.json shouldn't be added to LC solutions PR. Undo the changes

2022-10-07 16:07 UTC, vigneshshiv commented on package-lock.json
> +    "node_modules/@jridgewell/source-map": {
Why there's a change in package-lock.json file ? 
These files shouldn't be added for PR.

2022-10-07 16:09 UTC, wingkwong requested changes
don't commit package-lock.json

2022-10-07 16:09 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +};
Prefer K&R style

https://en.wikipedia.org/wiki/Indentation_style#K&R_style

2022-10-07 18:07 UTC, Srijita-Mandal commented
Changed the code indentation to K&R style. And didn't commit `package-lock.json` this time. I didn't really made any changes in the `json` file. Can't understand why this is changed. Please check if this is okay this time, if not, please tell me how to resolve it.

2022-10-08 03:43 UTC, wingkwong requested changes
As long as I see this package-lock.json in Files changed, I reject.

![image](https://user-images.githubusercontent.com/35857179/194686546-0d112616-70b4-48ed-bcf3-a9e7ec958fac.png)

2022-10-08 04:35 UTC, vigneshshiv commented
@Srijita-Mandal You need to reset your changes based on the last git commit (previous the this). Once you've done reset, your this changes will be unstaged. The undo the json changes and then commit only the relavant changes.

2022-10-08 04:54 UTC, Srijita-Mandal commented
I have made a new PR #225  regarding this issue, with preferable changes. Please review it.

2022-10-08 06:13 UTC, wingkwong commented
Closing this one. Move to PR225.

2022-10-08 06:13 UTC, closed without merging