solution: 2302-count-subarrays-with-score-less-than-K added
wingkwong/leetcode-the-hard-way pull request #210
Opened 2022-10-06 15:55 UTC by saloni33

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [x] Make sure you've explained your code well (write comments above each line - not inline)
- [x] Make sure you've written your explanation well and it is easy to understand for beginners
- [x] Make sure you've included Time & Space Complexity Analysis
- [x] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-06 16:51 UTC, vigneshshiv requested changes

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +For example, the score of [1, 2, 3, 4, 5] is (1 + 2 + 3 + 4 + 5) * 5 = 75.
Use LaTeX for numbers - $[1, 2, 3, 4, 5]$

Use bulletin for this line as per LC

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +Given a positive integer array nums and an integer k, return the number of non-empty subarrays of nums whose score is strictly less than k.
Follow the same format as per LC problem statement

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +
Remove an extra line space here

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +* $1 <= nums.length <= 105$
It's $10^5$, and correct it below constraints as well

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +## Approach : Sliding Window
Approach 1: Sliding Window

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +If we find a subarray nums[i] to nums[j] which has score less than k, we will update answer $ans += j - i + 1$ as there will be j - i + 1 total subarrays in total.
Apply LaTeX for nums[i] and wherever you have mentioned literals

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +example [1,2,3,4,5] and let i = 0, j = 2
Why separate example here ? If it's related to your explanation then add it there and explain with your example

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +            else {
else not align with code format. 
Please format it correctly

2022-10-06 16:51 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +<TabItem value="cpp" label="c++">
Correct this.. <TabItem value="c++" label="C++">

2022-10-06 17:26 UTC, saloni33 commented
@vigneshshiv  done the required changes

2022-10-07 05:35 UTC, vigneshshiv requested changes
Looks good, last round changes

2022-10-07 05:35 UTC, vigneshshiv commented on solutions/2300-2399/2302-count-subarrays-with-score-less-than-k.md
> +            else {
Why else is hanging separately.  Change it like below

```
If (condition) {
  // logic here
} else {
  // logic here
}
```

2022-10-07 14:48 UTC, saloni33 commented
@vigneshshiv done. Kindly check

2022-10-07 15:16 UTC, vigneshshiv approved these changes
LGTM! @wingkwong please proceed with final review.

2022-10-07 16:11 UTC, merged