New (Original) Explanation for solution #0623
wingkwong/leetcode-the-hard-way pull request #212
Opened 2022-10-06 17:40 UTC by The-Divyansh

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [ ] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [ ] Make sure you've followed the template format
- [ ] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [ ] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [ ] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [ ] Make sure you've explained your code well (write comments above each line - not inline)
- [ ] Make sure you've written your explanation well and it is easy to understand for beginners
- [ ] Make sure you've included Time & Space Complexity Analysis
- [ ] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-06 17:41 UTC, The-Divyansh commented
@wingkwong please check now. I have updated explanation of the approach

2022-10-07 16:17 UTC, vigneshshiv requested changes

2022-10-07 16:17 UTC, vigneshshiv commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +This approach uses a simple DFS approach. The recursive function `insert(node, currDepth, val, depth)` can be used to recursively reach a node where we need to insert two nodes.
Instead of backtick, apply LaTex in this Approach block.

2022-10-07 16:17 UTC, vigneshshiv commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +- currDepth -> the depth of current node `node`
Use LaTex in this line also Line 61, 63, 65, 67

2022-10-07 19:36 UTC, closed without merging

2022-10-08 03:19 UTC, wingkwong commented
You can just push your changes without closing the PR. The changes will be shown in this PR. This helps us to review easily with the previous history.