Added Solution #0623
wingkwong/leetcode-the-hard-way pull request #224
Opened 2022-10-07 19:38 UTC by The-Divyansh

Done all the changes suggested with proper formatting and LaTex

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [ ] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [ ] Make sure you've followed the template format
- [ ] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [ ] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [ ] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [ ] Make sure you've explained your code well (write comments above each line - not inline)
- [ ] Make sure you've written your explanation well and it is easy to understand for beginners
- [ ] Make sure you've included Time & Space Complexity Analysis
- [ ] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-07 19:39 UTC, The-Divyansh commented
@vigneshshiv @wingkwong  please check

2022-10-08 03:26 UTC, wingkwong commented
Just for record. Previous comments logged in #207 #212

2022-10-08 03:33 UTC, wingkwong requested changes
Don't close your PR. Push the changes and this PR will be updated automatically.

2022-10-08 03:33 UTC, wingkwong commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +        }
follow this coding style for all. i.e. the space and bracket position

```cpp
if (depth == 1) {
    TreeNode* newNode = new TreeNode(val);
    newNode->left = root;
    return newNode;
}
```

2022-10-08 03:33 UTC, wingkwong commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +        {
space and bracket. see below comment

2022-10-08 03:33 UTC, wingkwong commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +        insert(node->right, currDepth+1, val, depth);
space.

```
currDepth + 1
```

2022-10-08 03:33 UTC, wingkwong commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +        // recursive function for insertion of new nodes (similar to dfs)
`(similar to dfs)` can be deleted.

2022-10-08 03:33 UTC, wingkwong commented on solutions/0600-0699/0623-add-one-row-to-tree-medium.md
> +- depth -> the depth at which nodes are to be inserted
don't use `->` use `:`

2022-10-08 10:07 UTC, The-Divyansh commented
@wingkwong @vigneshshiv updated explanation and formatted the code. Please check

2022-10-08 13:18 UTC, wingkwong commented
I cleaned it up. Don't wanna waste time. This is what I'm expecting. https://github.com/wingkwong/leetcode-the-hard-way/pull/224/commits/cb7036df0d4c3a9efe87125becc49d9efabf0bc5.

2022-10-08 13:19 UTC, merged