Added the solution of problem 0102, with preferable changes
wingkwong/leetcode-the-hard-way pull request #225
Opened 2022-10-08 04:52 UTC by Srijita-Mandal

## Change Summary

Added the solution of the leetcode problem 102 with preferable changes

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [x] Make sure you've explained your code well (write comments above each line - not inline)
- [x] Make sure you've written your explanation well and it is easy to understand for beginners
- [x] Make sure you've included Time & Space Complexity Analysis
- [x] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-08 06:16 UTC, wingkwong requested changes
Hope it's final round

2022-10-08 06:16 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +public:
Adopt in K&R coding style. 

Ref: https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr

2022-10-08 06:16 UTC, wingkwong commented on solutions/0100-0199/0102-binary-tree-level-order-traversal-medium.md
> +**Space Complexity:**  $O(N)$
why O(N)? explain it to beginners.

2022-10-08 07:35 UTC, Srijita-Mandal commented
Committed the suggested changes.

2022-10-08 17:30 UTC, Srijita-Mandal commented
@wingkwong Are the changes okay now? Please review the PR.

2022-10-10 13:47 UTC, wingkwong commented
To save time, I've cleaned it up.

2022-11-01 02:41 UTC, merged