solution: 0015-3Sum added
wingkwong/leetcode-the-hard-way pull request #226
Opened 2022-10-08 05:59 UTC by saloni33

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [x] Make sure you've explained your code well (write comments above each line - not inline)
- [x] Make sure you've written your explanation well and it is easy to understand for beginners
- [x] Make sure you've included Time & Space Complexity Analysis
- [x] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-08 05:59 UTC, saloni33 commented
@vigneshshiv kindly review

2022-10-08 06:11 UTC, wingkwong requested changes

2022-10-08 06:11 UTC, wingkwong commented on solutions/0000-0099/0015-3Sum.md
> +If $nums[j] + nums[k] < target$, we need more positive numbers to make it 0, we will increament $j$ else we need more -negative numbers to make it 0, hence decreament $k$.
these will be packed together. Run the app locally to check. Don't use a markdown viewer.

2022-10-08 06:11 UTC, wingkwong commented on solutions/0000-0099/0015-3Sum.md
> +    }
1. need full code. i.e. include Class Solution .. not just the main function
2. need comments on your code

2022-10-08 06:26 UTC, saloni33 commented
Updated.

2022-10-08 13:35 UTC, wingkwong requested changes
1. your file name is incorrect. missing the difficulty at the end which causes the wrong ordering
2. put the time & space complexity before the code block
3. verify it locally first. it looks awful.
![image](https://user-images.githubusercontent.com/35857179/194710223-f34f2a2d-f29e-4244-af2a-151cfc77dc8c.png)

2022-10-09 16:35 UTC, wingkwong commented
Is it ready for review?

2022-10-10 12:29 UTC, saloni33 commented
> Is it ready for review?

Yes I have required changes

2022-10-10 13:02 UTC, wingkwong commented
Please click re-request review next time. Otherwise I'd assume it's still in progress.

2022-10-10 13:11 UTC, saloni33 commented
> Please click re-request review next time. Otherwise I'd assume it's still in progress.

okay

2022-10-10 14:01 UTC, wingkwong requested changes

2022-10-10 14:01 UTC, wingkwong commented on solutions/0000-0099/0015-3Sum-medium.md
> +        for (int i = 0 ; i < n-2 ; i++) {
`n - 2`

2022-10-10 14:01 UTC, wingkwong commented on solutions/0000-0099/0015-3Sum-medium.md
> +            if (i > 0 && nums[i] == nums[i-1])
`i - 1`

2022-10-12 12:26 UTC, saloni33 commented
@wingkwong kindly check

2022-10-19 14:27 UTC, wingkwong requested changes

2022-11-18 11:42 UTC, closed without merging