Update 0912-sort-an-array-medium.md
wingkwong/leetcode-the-hard-way pull request #228
Opened 2022-10-08 07:31 UTC by deepanshu-rawat6

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [X] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [X] Make sure you've followed the template format
- [X] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [X] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [X] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [X] Make sure you've explained your code well (write comments above each line - not inline)
- [X] Make sure you've written your explanation well and it is easy to understand for beginners
- [X] Make sure you've included Time & Space Complexity Analysis
- [X] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-08 07:52 UTC, wingkwong commented
DON'T close the PR and create a new every time you change something. You can just push your changes and they will be shown in the same PR.

ref: #179 #227

2022-10-08 13:25 UTC, wingkwong requested changes
1. Need more explanation on your approach and solutions. your audience is beginners. don't expect a few lines can explain everything.
2. Verify it locally first please

![image](https://user-images.githubusercontent.com/35857179/194709802-a8b4153c-279e-4fe6-944c-1a0ff3153b04.png)

2022-10-09 17:44 UTC, deepanshu-rawat6 commented
@wingkwong both detailed explanation and local verification has been made, kindly review these changes

2022-10-10 13:52 UTC, wingkwong requested changes

2022-10-10 13:52 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +    We merge the two subarrays( $left[]$ and $right[]$ ) into another array $mix[]$ . This merge operation stores elements from
same as above

2022-10-10 13:52 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +    // coppying and sorting sub-array by division on the basis of mid value
typo

2022-10-10 13:52 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +In this approach, merging happens $in-place$, changes are made in the original arrays itself by modifying the reference variables.
Incorrect usage of LaTex on `$in-place$`. Change it to `in-place`.

2022-10-10 16:05 UTC, deepanshu-rawat6 commented
@wingkwong I've fixed these changes now

2022-10-14 03:39 UTC, deepanshu-rawat6 commented
@wingkwong Ma'am can you please review my PR now?

2022-10-14 04:30 UTC, wingkwong requested changes

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +    Then, we return the sorted subarray into the above function call.
please run the app locally to verify. the content is all packed which is quite hard to read.

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +    Then, we place the sorted elements from $mix$ into $arr$ , finally changes in $arr$ have been made in-place.
same as above

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +In this approach, merging happen in `seperate array` of size, then it is passed on in the above function calls.
remove backticks

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +In this approach, merging happens `in-place`, changes are made in the original arrays itself by modifying the reference variables.
remove backticks

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +        arr[s+l] = mix[l];
add space.

```
arr[s + l]
```

2022-10-14 04:30 UTC, wingkwong commented on solutions/0900-0999/0912-sort-an-array-medium.md
> +    // Dividing sub-arrays by mid values till, sub-array length reaches one
start with lower case

2022-10-14 04:41 UTC, deepanshu-rawat6 commented
@wingkwong can I add explanation in bullet points?

2022-10-14 04:42 UTC, wingkwong commented
Yes. Go ahead. Please check it locally before requesting review.

2022-10-14 04:52 UTC, deepanshu-rawat6 commented
@wingkwong I have now verified the changes locally

2022-10-18 03:25 UTC, closed without merging