Updated the code by reducing the size of comments for better readability
wingkwong/leetcode-the-hard-way pull request #229
Opened 2022-10-08 10:03 UTC by Pranathi-star

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [x] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [x] Make sure you've followed the template format
- [x] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [x] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [x] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [x] Make sure you've explained your code well (write comments above each line - not inline)
- [x] Make sure you've written your explanation well and it is easy to understand for beginners
- [x] Make sure you've included Time & Space Complexity Analysis
- [x] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-08 10:12 UTC, wingkwong commented
You are creating 2 PRs (another one: https://github.com/wingkwong/leetcode-the-hard-way/pull/206) with 2 same files which is quite confusing which is which.

2022-10-08 11:30 UTC, Pranathi-star commented
I am sorry for the inconvenience. This PR contains the updated code for both solutions. Please ignore the previous one. I will close that.

2022-10-08 13:41 UTC, wingkwong requested changes
Hope it's the final round.

2022-10-08 13:41 UTC, wingkwong commented on solutions/0200-0299/0289-game-of-life-medium.md
> +# 0289 - Game of Life
`# 0289 - Game of Life (Medium)`

2022-10-08 13:41 UTC, wingkwong commented on solutions/0200-0299/0289-game-of-life-medium.md
> +class Solution:
Format your code well please. The indentation looks awful in code. Even tho it looks ok in UI.

2022-10-08 13:41 UTC, wingkwong commented on solutions/0900-0999/0994-rotting-oranges-medium.md
> +# 0994 - Rotting Oranges
`# 0994 - Rotting Oranges (Medium)`

2022-11-01 16:08 UTC, wingkwong commented
any update?

2022-11-18 11:42 UTC, wingkwong commented
Closing due to inactivity.

2022-11-18 11:42 UTC, closed without merging