added_leet_code_1590
wingkwong/leetcode-the-hard-way pull request #231
Opened 2022-10-08 10:57 UTC by Dark-Hope-tech

## Change Summary

Provide summary of changes with issue number if any.

## Checklist

**If you haven't fulfilled the below requirements, your PR won't be reviewed.**

### General 

- [ ] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [ ] Make sure you've followed the template format
- [ ] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [ ] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [ ] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
```

</TabItem>

</Tabs>
````
- [ ] Make sure you've explained your code well (write comments above each line - not inline)
- [ ] Make sure you've written your explanation well and it is easy to understand for beginners
- [ ] Make sure you've included Time & Space Complexity Analysis
- [ ] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-08 11:36 UTC, wingkwong requested changes

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +  Author: @wingkwong |
don't use my name

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +  https://leetcode.com/problems/make-sum-divisible-by-p/solutions/
remove /solutions

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +https://leetcode.com/problems/make-sum-divisible-by-p/solutions/
remove /solutions

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +i.e curr = index of (p - suff[i+1])%p
```
 Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
```

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +	}
Change all to K&R Brace style. i.e.

```cpp
for (int i = n - 1; i >= 0; i--) {
    sum += nums[i];
    suff[i] = sum % p;
}   
```

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +			// complement of suff[i+1]
add space. `i + 1`

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +	if (rem == 0)
`rem` is not used below. you can just use `if (sum % p == 0)`.

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +The only extra memory we are using is the suffix array and a HashMap.
move these out. put them before the code block.

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +				// remove elements from m[curr]+1 to i
add space. `m[curr] + 1`

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +	// defualt sum of array as none element is selected.
typo

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +```java
apply the same changes commented in c++ solution

2022-10-08 11:36 UTC, wingkwong commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +int minSubarray(vector<int> &nums, int p)
include whole code, not just the function

```cpp
class Solution {
public:
   // ...
};
```

2022-10-08 13:20 UTC, Dark-Hope-tech commented
@wingkwong @vigneshshiv Please check now

2022-10-08 13:30 UTC, wingkwong requested changes
You are responsible to check it first and make sure your PR is really ready for review. 

![image](https://user-images.githubusercontent.com/35857179/194710033-cf9a5f6c-a3af-48c8-9bf4-1de8f3d54fc6.png)

![image](https://user-images.githubusercontent.com/35857179/194709965-0ebe8312-714b-40a4-aa24-cc67b25ab738.png)

2022-10-08 15:42 UTC, Dark-Hope-tech commented
@wingkwong I have made changes . Please check now

2022-10-10 14:11 UTC, Dark-Hope-tech commented on solutions/1500-1599/1590-make_sum_divisible_by_p-medium.md
> +We first compute the sum of array an then take its modulo wtih given interger p, if this number is 0, that's awesome return 0 else we somehow have to make this number 0. For this we will remove some
@wingkwong check now .. final changes done

2022-10-19 13:52 UTC, Dark-Hope-tech commented
can i have updates regrading PR

2022-10-19 14:23 UTC, wingkwong approved these changes

2022-11-01 02:42 UTC, merged