Solution for 0240. Search in a matrix II added
wingkwong/leetcode-the-hard-way pull request #260
Opened 2022-10-11 08:45 UTC by A-Spiral-Forge

## Change Summary

I added the 3 approaches for leetcode question 240 Search in a matrix II.

## Checklist

**Ideally all of them should be checked. If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed.**

### General 

- [X] Make sure you've read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) 
- [X] Make sure you've followed the template format
- [X] Make sure you've started the app locally and verified all the content and all links (if applicable) must be accessible correctly
- [X] Make sure you've applied LaTex for variables, formulas and time / space complexity instead of using backticks
- [X] Make sure you've formatted your code well (Code Block is rendered using `<Tabs/>`)
      Below is a C++ example. You can include multiple langs using `<TabItem/>` if necessary
      
````
<Tabs>

<TabItem value="cpp" label="C++">
<SolutionAuthor name="@YOUR_ALIAS"/>

```cpp
// Your code goes here
// Prefer K&R Coding style
// See https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr for example
```

</TabItem>

</Tabs>
````
- [X] Make sure you've explained your code well (write comments above each line - not inline)
- [X] Make sure you've written your explanation well and it is easy to understand for beginners
- [X] Make sure you've included Time & Space Complexity Analysis
- [X] Make sure you've included a meaningful approach name for your solution. Don't leave it blank. e.g. `## Approach 1: Two Pointers`.

### For Tutorial Articles

- [ ] Make sure you've explained your topic using 1 - 3 LC problems rather than using external problems. Solutions must be taken with explanations as well.
- [ ] Make sure you've provided suggested problems at the end using the given format. See [here](https://raw.githubusercontent.com/wingkwong/leetcode-the-hard-way/main/tutorials/math/number-theory/binary-exponentiation.md) as an example. If the target solution is not available, leave `solutionLink` blank.
- [ ] Make sure you've given credits / references if you use external resources. For an image, give credit under it. Otherwise, add a new section called References at the end (after Suggested Problems).

2022-10-11 08:56 UTC, wingkwong requested changes
1. for all the code, please submit once to verify.
2. add some comments on your code also

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +```
wrong format + no LaTex

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +	m, n = len(matrix), len(matrix) and len(matrix[0])
unwanted spaces

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +    if(n == 0) {
please submit once to make sure your code works first.

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +    }
why differ than your above sols?

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +```
same as above.

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +    int row = 0, col = m-1;
`m - 1` instead of `m-1`.

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +	r, c = 0, n-1
`n - 1`

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +
time complexity & space complexity??

2022-10-11 08:56 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +* then we caclulate the end row (not included) the target might occurs (using upper_bound binary search).
typo

2022-10-11 13:28 UTC, A-Spiral-Forge commented
@wingkwong I made the changes as suggested by you. Kindly review it.

2022-10-31 10:00 UTC, A-Spiral-Forge commented
@wingkwong can you please review it.

2022-10-31 10:05 UTC, wingkwong requested changes
1. Follow [K&R Coding style](https://gist.github.com/jesseschalken/0f47a2b5a738ced9c845#why-kr)
2. Include full solution. not just the function.

2022-10-31 10:05 UTC, wingkwong commented on solutions/0200-0299/0240-search-in-a-matrix-II-medium.md
> +* Start iterating the matrix from top right corner of the matrix, that is `matrix[0][size of column -1]`.
space

2022-10-31 11:04 UTC, A-Spiral-Forge commented
@wingkwong I think now it's fine

2022-10-31 11:30 UTC, wingkwong reviewed
Not really. There should be a space before `(`

```
for(
if(
while(
```

2022-10-31 14:45 UTC, A-Spiral-Forge commented
@wingkwong now??

2022-10-31 15:21 UTC, wingkwong requested changes
Please run your solutions on LC. Some got compile error.

2022-11-18 11:42 UTC, wingkwong commented
Closing due to inactivity.

2022-11-18 11:42 UTC, closed without merging