Bubble Sort Tutorial
wingkwong/leetcode-the-hard-way pull request #270
Opened 2022-10-14 13:05 UTC by RadhikaChhabra17

Tutorial Writeup - Bubble Sort #93

2022-10-14 13:12 UTC, wingkwong requested changes
Please look at the checklist first as well as other tutorials for reference.

2022-10-16 07:28 UTC, RadhikaChhabra17 commented
Can you please review it and let me know if any changes are required.

2022-10-16 07:52 UTC, wingkwong requested changes
Please look at the checklist first as well as other tutorials for reference.

2022-10-17 20:15 UTC, RadhikaChhabra17 commented
Hi, it would be helpful if you can be more specific about change.

2022-10-18 02:23 UTC, wingkwong requested changes

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +
unexpected line breaks

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +
there's lots of extra line breaks

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +	i = 0 -> 2,3,4,5,6
put it outside and present it better

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +}
code should be in <Tabs/> .. just like what you did in solutions.

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +This shows that it is an inline sorting.
1. these are packed together. Verify it in your local by running the app. (Not looking at markdown editor)
2. as stated in checklist, you need to apply LaTex on variables / formula / time & space complexity

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +        //Working for even indices
// work for even indices

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +            for (int j = i+2; j < nums.size(); j += 2){
i + 2

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +                //sorting in non-decreasing order
// sort in non-decreasing order

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +        //Working for odd indicies
// work for odd indicies

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +           for (int j = i+2; j < nums.size(); j += 2){
i + 2

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +               //sorting in non-increasing order
// sort in non-increasing order

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +Bubble Sort is a sorting algorithm which compares the adjacent elements and swap their positions if they are placed in wrong order. At max, we need to compare adjacent elements for (n-1) iterations w
1. Apply LaTex on `n-1`, `n`. e.g. `$n - 1$` and `$n$`
2. add a space after the word `larger`

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +	for(int i=0; i<n-1 && check; i++) {
have you explained why we need `check` here?

2022-10-18 02:23 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +				arr[j+1] = temp;
why not just `swap(arr[j], arr[j + 1])` ?

2022-10-18 10:41 UTC, RadhikaChhabra17 commented
I have made the required changes. Please look into it and let me know if any change is required.

2022-10-18 11:13 UTC, wingkwong requested changes

2022-10-18 11:13 UTC, wingkwong commented on solutions/0000-0099/0075-sort-colors-medium.md
> +```c++
same. K&R coding style & spacing.

2022-10-18 11:13 UTC, wingkwong commented on solutions/0100-0199/0148-sort-list-medium.md
> +class Solution {
same. K&R coding style & spacing. comments start with lower case

2022-10-18 11:13 UTC, wingkwong commented on solutions/0100-0199/0148-sort-list-medium.md
> + # Approach 2: Bubble Sort
remove extra space

2022-10-18 11:13 UTC, wingkwong commented on solutions/0100-0199/0148-sort-list-medium.md
> + <Tabs>
remove extra space and add a line break

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +    index = 3 -> 3,4,2,5,6
not aligned

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +arr = {3,6,4,2,5}:
`$arr = [3, 6, 4, 2, 5]$`

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +The syntax that we are using is `cpp`, please refer to your own language of preference if needed.
no need to mention this line.

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +We can use a variable *check* to see if there is swap in one pass or not. If there is no swapping in one pass, they we don't have to check for other pass.
prefer to show the standard bubble sort code first. then mention how to optimize it using `check`. besides, this line is not clean.

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +	for(int i = 0; i < n - 1 && check; i++) {
there should be a space after `for`. please check all.

`for (int i = 0; i < n - 1 && check; i++) {`

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +			}
1. poor indentation
2. add a space after `if`

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +        //For even indices
i expected you to copy the line in my previous comments...

1. lower case
2. add a space after `//`

apply to all.

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +So, Worst Case Time Complexity = $$(n - 1)$$ + $$(n - 2)$$ + $$(n - 3)$$ + ... + 1 = $$O(n^2)$$
Too tedious. Use

```
$(n - 1) + (n - 2) + (n - 3) + ... + 1 = O(n ^ 2)$
```

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +This shows that it is an inline sorting.
these will be rendered in the same line in the app. please verify it locally.

2022-10-18 11:13 UTC, wingkwong commented on tutorials/basic-topics/sorting/bubble-sort.md
> +	index = 0 -> 2,3,4,5,6
not intuitive at all

2022-10-22 03:05 UTC, wingkwong approved these changes
Cleaned up a bit.

2022-10-22 03:12 UTC, wingkwong commented
@RadhikaChhabra17 Your solution gives TLE in 0148 - Sort List (Medium). I removed it. Besides, please take a look the commits that I've made above. You will have ideas of what you've missed. I'll merge this. Thanks.

2022-10-22 03:12 UTC, merged